/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  numeric,
  boolean,
  timestamp,
  serial,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_products_claims_sentiment = pgEnum('enum_products_claims_sentiment', [
  'positive',
  'negative',
])
export const enum_products_status = pgEnum('enum_products_status', ['draft', 'published'])
export const enum__products_v_version_claims_sentiment = pgEnum(
  'enum__products_v_version_claims_sentiment',
  ['positive', 'negative'],
)
export const enum__products_v_version_status = pgEnum('enum__products_v_version_status', [
  'draft',
  'published',
])
export const enum_categories_app_category = pgEnum('enum_categories_app_category', [
  'FinanceApplication',
  'ShoppingApplication',
  'LifestyleApplication',
  'TravelApplication',
  'HealthApplication',
  'EntertainmentApplication',
  'UtilitiesApplication',
])
export const enum_best_lists_rank_by = pgEnum('enum_best_lists_rank_by', [
  'satisfaction',
  'fewest-problems',
])
export const enum_best_lists_status = pgEnum('enum_best_lists_status', ['draft', 'published'])
export const enum__best_lists_v_version_rank_by = pgEnum('enum__best_lists_v_version_rank_by', [
  'satisfaction',
  'fewest-problems',
])
export const enum__best_lists_v_version_status = pgEnum('enum__best_lists_v_version_status', [
  'draft',
  'published',
])
export const enum_comparisons_status = pgEnum('enum_comparisons_status', ['draft', 'published'])
export const enum__comparisons_v_version_status = pgEnum('enum__comparisons_v_version_status', [
  'draft',
  'published',
])
export const enum_guides_status = pgEnum('enum_guides_status', ['draft', 'published'])
export const enum__guides_v_version_status = pgEnum('enum__guides_v_version_status', [
  'draft',
  'published',
])
export const enum_review_requests_status = pgEnum('enum_review_requests_status', [
  'new',
  'queued',
  'added',
  'declined',
])
export const enum_sources_kind = pgEnum('enum_sources_kind', [
  'marketplace',
  'brand-store',
  'app-store',
  'community',
  'video',
])
export const enum_reviews_sentiment = pgEnum('enum_reviews_sentiment', [
  'positive',
  'neutral',
  'negative',
])
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'editor'])

export const products_claims = pgTable(
  'products_claims',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    sentiment: enum_products_claims_sentiment('sentiment'),
    aspect: integer('aspect_id').references(() => aspects.id, {
      onDelete: 'set null',
    }),
    text: varchar('text'),
  },
  (columns) => [
    index('products_claims_order_idx').on(columns._order),
    index('products_claims_parent_id_idx').on(columns._parentID),
    index('products_claims_aspect_idx').on(columns.aspect),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_claims_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_faq = pgTable(
  'products_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    q: varchar('q'),
    a: varchar('a'),
  },
  (columns) => [
    index('products_faq_order_idx').on(columns._order),
    index('products_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_offers = pgTable(
  'products_offers',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    source: integer('source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    price: numeric('price', { mode: 'number' }),
    mrp: numeric('mrp', { mode: 'number' }),
    inStock: boolean('in_stock').default(true),
    url: varchar('url'),
    checkedAt: timestamp('checked_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('products_offers_order_idx').on(columns._order),
    index('products_offers_parent_id_idx').on(columns._parentID),
    index('products_offers_source_idx').on(columns.source),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_offers_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_specs = pgTable(
  'products_specs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    value: varchar('value'),
  },
  (columns) => [
    index('products_specs_order_idx').on(columns._order),
    index('products_specs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_specs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_platform_stats = pgTable(
  'products_platform_stats',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    source: integer('source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    rating: numeric('rating', { mode: 'number' }),
    total: numeric('total', { mode: 'number' }),
  },
  (columns) => [
    index('products_platform_stats_order_idx').on(columns._order),
    index('products_platform_stats_parent_id_idx').on(columns._parentID),
    index('products_platform_stats_source_idx').on(columns.source),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_platform_stats_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    shortName: varchar('short_name'),
    brand: integer('brand_id').references(() => brands.id, {
      onDelete: 'set null',
    }),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    variant: varchar('variant'),
    sample: boolean('sample'),
    answer: varchar('answer'),
    verdictBody: varchar('verdict_body'),
    valueQuantity: numeric('value_quantity', { mode: 'number' }).default(0),
    flipkartUrl: varchar('flipkart_url'),
    playStoreId: varchar('play_store_id'),
    appStoreId: varchar('app_store_id'),
    redditPhrases: varchar('reddit_phrases'),
    dataUpdatedAt: timestamp('data_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    slug: varchar('slug'),
    author: integer('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    approvedAt: timestamp('approved_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_products_status('_status').default('draft'),
  },
  (columns) => [
    index('products_brand_idx').on(columns.brand),
    index('products_category_idx').on(columns.category),
    uniqueIndex('products_slug_idx').on(columns.slug),
    index('products_author_idx').on(columns.author),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
    index('products__status_idx').on(columns._status),
  ],
)

export const _products_v_version_claims = pgTable(
  '_products_v_version_claims',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    sentiment: enum__products_v_version_claims_sentiment('sentiment'),
    aspect: integer('aspect_id').references(() => aspects.id, {
      onDelete: 'set null',
    }),
    text: varchar('text'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_claims_order_idx').on(columns._order),
    index('_products_v_version_claims_parent_id_idx').on(columns._parentID),
    index('_products_v_version_claims_aspect_idx').on(columns.aspect),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_claims_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_faq = pgTable(
  '_products_v_version_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    q: varchar('q'),
    a: varchar('a'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_faq_order_idx').on(columns._order),
    index('_products_v_version_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_offers = pgTable(
  '_products_v_version_offers',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    source: integer('source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    price: numeric('price', { mode: 'number' }),
    mrp: numeric('mrp', { mode: 'number' }),
    inStock: boolean('in_stock').default(true),
    url: varchar('url'),
    checkedAt: timestamp('checked_at', { mode: 'string', withTimezone: true, precision: 3 }),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_offers_order_idx').on(columns._order),
    index('_products_v_version_offers_parent_id_idx').on(columns._parentID),
    index('_products_v_version_offers_source_idx').on(columns.source),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_offers_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_specs = pgTable(
  '_products_v_version_specs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    label: varchar('label'),
    value: varchar('value'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_specs_order_idx').on(columns._order),
    index('_products_v_version_specs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_specs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_platform_stats = pgTable(
  '_products_v_version_platform_stats',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    source: integer('source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    rating: numeric('rating', { mode: 'number' }),
    total: numeric('total', { mode: 'number' }),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_platform_stats_order_idx').on(columns._order),
    index('_products_v_version_platform_stats_parent_id_idx').on(columns._parentID),
    index('_products_v_version_platform_stats_source_idx').on(columns.source),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_platform_stats_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v = pgTable(
  '_products_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_shortName: varchar('version_short_name'),
    version_brand: integer('version_brand_id').references(() => brands.id, {
      onDelete: 'set null',
    }),
    version_category: integer('version_category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_variant: varchar('version_variant'),
    version_sample: boolean('version_sample'),
    version_answer: varchar('version_answer'),
    version_verdictBody: varchar('version_verdict_body'),
    version_valueQuantity: numeric('version_value_quantity', { mode: 'number' }).default(0),
    version_flipkartUrl: varchar('version_flipkart_url'),
    version_playStoreId: varchar('version_play_store_id'),
    version_appStoreId: varchar('version_app_store_id'),
    version_redditPhrases: varchar('version_reddit_phrases'),
    version_dataUpdatedAt: timestamp('version_data_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_slug: varchar('version_slug'),
    version_author: integer('version_author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    version_approvedAt: timestamp('version_approved_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__products_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_products_v_parent_idx').on(columns.parent),
    index('_products_v_version_version_brand_idx').on(columns.version_brand),
    index('_products_v_version_version_category_idx').on(columns.version_category),
    index('_products_v_version_version_slug_idx').on(columns.version_slug),
    index('_products_v_version_version_author_idx').on(columns.version_author),
    index('_products_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_products_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_products_v_version_version__status_idx').on(columns.version__status),
    index('_products_v_created_at_idx').on(columns.createdAt),
    index('_products_v_updated_at_idx').on(columns.updatedAt),
    index('_products_v_latest_idx').on(columns.latest),
  ],
)

export const categories_measures = pgTable(
  'categories_measures',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    aspect: integer('aspect_id')
      .notNull()
      .references(() => aspects.id, {
        onDelete: 'set null',
      }),
    dealBreaker: boolean('deal_breaker'),
    weight: numeric('weight', { mode: 'number' }).default(1),
  },
  (columns) => [
    index('categories_measures_order_idx').on(columns._order),
    index('categories_measures_parent_id_idx').on(columns._parentID),
    index('categories_measures_aspect_idx').on(columns.aspect),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [categories.id],
      name: 'categories_measures_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const categories_faq = pgTable(
  'categories_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    q: varchar('q').notNull(),
    a: varchar('a').notNull(),
  },
  (columns) => [
    index('categories_faq_order_idx').on(columns._order),
    index('categories_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [categories.id],
      name: 'categories_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    parent: integer('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    tagline: varchar('tagline').notNull(),
    intro: varchar('intro'),
    valueMetric_label: varchar('value_metric_label'),
    valueMetric_basis: numeric('value_metric_basis', { mode: 'number' }),
    isApp: boolean('is_app'),
    appCategory: enum_categories_app_category('app_category'),
    slug: varchar('slug').notNull(),
    refreshDays: numeric('refresh_days', { mode: 'number' }).default(21),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_parent_idx').on(columns.parent),
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const brands_same_as = pgTable(
  'brands_same_as',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('brands_same_as_order_idx').on(columns._order),
    index('brands_same_as_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [brands.id],
      name: 'brands_same_as_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const brands = pgTable(
  'brands',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    about: varchar('about'),
    website: varchar('website'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('brands_logo_idx').on(columns.logo),
    uniqueIndex('brands_slug_idx').on(columns.slug),
    index('brands_updated_at_idx').on(columns.updatedAt),
    index('brands_created_at_idx').on(columns.createdAt),
  ],
)

export const best_lists_faq = pgTable(
  'best_lists_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    q: varchar('q'),
    a: varchar('a'),
  },
  (columns) => [
    index('best_lists_faq_order_idx').on(columns._order),
    index('best_lists_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [best_lists.id],
      name: 'best_lists_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const best_lists = pgTable(
  'best_lists',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    qualifier: varchar('qualifier'),
    intro: varchar('intro'),
    rankBy: enum_best_lists_rank_by('rank_by').default('satisfaction'),
    aspect: integer('aspect_id').references(() => aspects.id, {
      onDelete: 'set null',
    }),
    maxPrice: numeric('max_price', { mode: 'number' }),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_best_lists_status('_status').default('draft'),
  },
  (columns) => [
    index('best_lists_category_idx').on(columns.category),
    index('best_lists_aspect_idx').on(columns.aspect),
    uniqueIndex('best_lists_slug_idx').on(columns.slug),
    index('best_lists_updated_at_idx').on(columns.updatedAt),
    index('best_lists_created_at_idx').on(columns.createdAt),
    index('best_lists__status_idx').on(columns._status),
  ],
)

export const _best_lists_v_version_faq = pgTable(
  '_best_lists_v_version_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    q: varchar('q'),
    a: varchar('a'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_best_lists_v_version_faq_order_idx').on(columns._order),
    index('_best_lists_v_version_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_best_lists_v.id],
      name: '_best_lists_v_version_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _best_lists_v = pgTable(
  '_best_lists_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => best_lists.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_category: integer('version_category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_qualifier: varchar('version_qualifier'),
    version_intro: varchar('version_intro'),
    version_rankBy: enum__best_lists_v_version_rank_by('version_rank_by').default('satisfaction'),
    version_aspect: integer('version_aspect_id').references(() => aspects.id, {
      onDelete: 'set null',
    }),
    version_maxPrice: numeric('version_max_price', { mode: 'number' }),
    version_slug: varchar('version_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__best_lists_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_best_lists_v_parent_idx').on(columns.parent),
    index('_best_lists_v_version_version_category_idx').on(columns.version_category),
    index('_best_lists_v_version_version_aspect_idx').on(columns.version_aspect),
    index('_best_lists_v_version_version_slug_idx').on(columns.version_slug),
    index('_best_lists_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_best_lists_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_best_lists_v_version_version__status_idx').on(columns.version__status),
    index('_best_lists_v_created_at_idx').on(columns.createdAt),
    index('_best_lists_v_updated_at_idx').on(columns.updatedAt),
    index('_best_lists_v_latest_idx').on(columns.latest),
  ],
)

export const comparisons_pick_if = pgTable(
  'comparisons_pick_if',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    product: integer('product_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    text: varchar('text'),
  },
  (columns) => [
    index('comparisons_pick_if_order_idx').on(columns._order),
    index('comparisons_pick_if_parent_id_idx').on(columns._parentID),
    index('comparisons_pick_if_product_idx').on(columns.product),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [comparisons.id],
      name: 'comparisons_pick_if_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const comparisons = pgTable(
  'comparisons',
  {
    id: serial('id').primaryKey(),
    judgement: varchar('judgement'),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_comparisons_status('_status').default('draft'),
  },
  (columns) => [
    index('comparisons_category_idx').on(columns.category),
    uniqueIndex('comparisons_slug_idx').on(columns.slug),
    index('comparisons_updated_at_idx').on(columns.updatedAt),
    index('comparisons_created_at_idx').on(columns.createdAt),
    index('comparisons__status_idx').on(columns._status),
  ],
)

export const comparisons_rels = pgTable(
  'comparisons_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
  },
  (columns) => [
    index('comparisons_rels_order_idx').on(columns.order),
    index('comparisons_rels_parent_idx').on(columns.parent),
    index('comparisons_rels_path_idx').on(columns.path),
    index('comparisons_rels_products_id_idx').on(columns.productsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [comparisons.id],
      name: 'comparisons_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'comparisons_rels_products_fk',
    }).onDelete('cascade'),
  ],
)

export const _comparisons_v_version_pick_if = pgTable(
  '_comparisons_v_version_pick_if',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    product: integer('product_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    text: varchar('text'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_comparisons_v_version_pick_if_order_idx').on(columns._order),
    index('_comparisons_v_version_pick_if_parent_id_idx').on(columns._parentID),
    index('_comparisons_v_version_pick_if_product_idx').on(columns.product),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_comparisons_v.id],
      name: '_comparisons_v_version_pick_if_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _comparisons_v = pgTable(
  '_comparisons_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => comparisons.id, {
      onDelete: 'set null',
    }),
    version_judgement: varchar('version_judgement'),
    version_category: integer('version_category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_slug: varchar('version_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__comparisons_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_comparisons_v_parent_idx').on(columns.parent),
    index('_comparisons_v_version_version_category_idx').on(columns.version_category),
    index('_comparisons_v_version_version_slug_idx').on(columns.version_slug),
    index('_comparisons_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_comparisons_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_comparisons_v_version_version__status_idx').on(columns.version__status),
    index('_comparisons_v_created_at_idx').on(columns.createdAt),
    index('_comparisons_v_updated_at_idx').on(columns.updatedAt),
    index('_comparisons_v_latest_idx').on(columns.latest),
  ],
)

export const _comparisons_v_rels = pgTable(
  '_comparisons_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
  },
  (columns) => [
    index('_comparisons_v_rels_order_idx').on(columns.order),
    index('_comparisons_v_rels_parent_idx').on(columns.parent),
    index('_comparisons_v_rels_path_idx').on(columns.path),
    index('_comparisons_v_rels_products_id_idx').on(columns.productsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_comparisons_v.id],
      name: '_comparisons_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: '_comparisons_v_rels_products_fk',
    }).onDelete('cascade'),
  ],
)

export const guides_faq = pgTable(
  'guides_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    q: varchar('q'),
    a: varchar('a'),
  },
  (columns) => [
    index('guides_faq_order_idx').on(columns._order),
    index('guides_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [guides.id],
      name: 'guides_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const guides = pgTable(
  'guides',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    aspect: integer('aspect_id').references(() => aspects.id, {
      onDelete: 'set null',
    }),
    section: integer('section_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    explainer: varchar('explainer'),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_guides_status('_status').default('draft'),
  },
  (columns) => [
    index('guides_aspect_idx').on(columns.aspect),
    index('guides_section_idx').on(columns.section),
    uniqueIndex('guides_slug_idx').on(columns.slug),
    index('guides_updated_at_idx').on(columns.updatedAt),
    index('guides_created_at_idx').on(columns.createdAt),
    index('guides__status_idx').on(columns._status),
  ],
)

export const _guides_v_version_faq = pgTable(
  '_guides_v_version_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    q: varchar('q'),
    a: varchar('a'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_guides_v_version_faq_order_idx').on(columns._order),
    index('_guides_v_version_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_guides_v.id],
      name: '_guides_v_version_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _guides_v = pgTable(
  '_guides_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => guides.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_aspect: integer('version_aspect_id').references(() => aspects.id, {
      onDelete: 'set null',
    }),
    version_section: integer('version_section_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_explainer: varchar('version_explainer'),
    version_slug: varchar('version_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__guides_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_guides_v_parent_idx').on(columns.parent),
    index('_guides_v_version_version_aspect_idx').on(columns.version_aspect),
    index('_guides_v_version_version_section_idx').on(columns.version_section),
    index('_guides_v_version_version_slug_idx').on(columns.version_slug),
    index('_guides_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_guides_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_guides_v_version_version__status_idx').on(columns.version__status),
    index('_guides_v_created_at_idx').on(columns.createdAt),
    index('_guides_v_updated_at_idx').on(columns.updatedAt),
    index('_guides_v_latest_idx').on(columns.latest),
  ],
)

export const review_requests_subscribers = pgTable(
  'review_requests_subscribers',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    email: varchar('email').notNull(),
  },
  (columns) => [
    index('review_requests_subscribers_order_idx').on(columns._order),
    index('review_requests_subscribers_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [review_requests.id],
      name: 'review_requests_subscribers_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const review_requests = pgTable(
  'review_requests',
  {
    id: serial('id').primaryKey(),
    query: varchar('query').notNull(),
    productUrl: varchar('product_url'),
    product: integer('product_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    notes: varchar('notes'),
    status: enum_review_requests_status('status').notNull().default('new'),
    requestCount: numeric('request_count', { mode: 'number' }).notNull().default(1),
    lastRequestedAt: timestamp('last_requested_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    normalizedQuery: varchar('normalized_query').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('review_requests_product_idx').on(columns.product),
    index('review_requests_normalized_query_idx').on(columns.normalizedQuery),
    index('review_requests_updated_at_idx').on(columns.updatedAt),
    index('review_requests_created_at_idx').on(columns.createdAt),
  ],
)

export const aspects = pgTable(
  'aspects',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    question: varchar('question').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('aspects_slug_idx').on(columns.slug),
    index('aspects_updated_at_idx').on(columns.updatedAt),
    index('aspects_created_at_idx').on(columns.createdAt),
  ],
)

export const sources = pgTable(
  'sources',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    kind: enum_sources_kind('kind').notNull(),
    weight: numeric('weight', { mode: 'number' }).notNull().default(1),
    hasRatings: boolean('has_ratings').default(true),
    collection: varchar('collection').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('sources_slug_idx').on(columns.slug),
    index('sources_updated_at_idx').on(columns.updatedAt),
    index('sources_created_at_idx').on(columns.createdAt),
  ],
)

export const reviews = pgTable(
  'reviews',
  {
    id: serial('id').primaryKey(),
    hidden: boolean('hidden'),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    body: varchar('body').notNull(),
    source: varchar('source').notNull(),
    rating: numeric('rating', { mode: 'number' }),
    sentiment: enum_reviews_sentiment('sentiment'),
    author: varchar('author'),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }),
    verified: boolean('verified'),
    credibility: numeric('credibility', { mode: 'number' }),
    url: varchar('url'),
    aspects: jsonb('aspects'),
    original: jsonb('original'),
    externalId: varchar('external_id'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('reviews_product_idx').on(columns.product),
    index('reviews_source_idx').on(columns.source),
    uniqueIndex('reviews_external_id_idx').on(columns.externalId),
    index('reviews_updated_at_idx').on(columns.updatedAt),
    index('reviews_created_at_idx').on(columns.createdAt),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    role: enum_users_role('role').default('editor'),
    jobTitle: varchar('job_title').default('Editor'),
    bio: varchar('bio'),
    credentials: varchar('credentials'),
    photo: integer('photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    resetPasswordRequestedAt: timestamp('reset_password_requested_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    uniqueIndex('users_slug_idx').on(columns.slug),
    index('users_photo_idx').on(columns.photo),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
    categoriesID: integer('categories_id'),
    brandsID: integer('brands_id'),
    'best-listsID': integer('best_lists_id'),
    comparisonsID: integer('comparisons_id'),
    guidesID: integer('guides_id'),
    'review-requestsID': integer('review_requests_id'),
    aspectsID: integer('aspects_id'),
    sourcesID: integer('sources_id'),
    reviewsID: integer('reviews_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_brands_id_idx').on(columns.brandsID),
    index('payload_locked_documents_rels_best_lists_id_idx').on(columns['best-listsID']),
    index('payload_locked_documents_rels_comparisons_id_idx').on(columns.comparisonsID),
    index('payload_locked_documents_rels_guides_id_idx').on(columns.guidesID),
    index('payload_locked_documents_rels_review_requests_id_idx').on(columns['review-requestsID']),
    index('payload_locked_documents_rels_aspects_id_idx').on(columns.aspectsID),
    index('payload_locked_documents_rels_sources_id_idx').on(columns.sourcesID),
    index('payload_locked_documents_rels_reviews_id_idx').on(columns.reviewsID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['brandsID']],
      foreignColumns: [brands.id],
      name: 'payload_locked_documents_rels_brands_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['best-listsID']],
      foreignColumns: [best_lists.id],
      name: 'payload_locked_documents_rels_best_lists_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['comparisonsID']],
      foreignColumns: [comparisons.id],
      name: 'payload_locked_documents_rels_comparisons_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['guidesID']],
      foreignColumns: [guides.id],
      name: 'payload_locked_documents_rels_guides_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['review-requestsID']],
      foreignColumns: [review_requests.id],
      name: 'payload_locked_documents_rels_review_requests_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['aspectsID']],
      foreignColumns: [aspects.id],
      name: 'payload_locked_documents_rels_aspects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: 'payload_locked_documents_rels_sources_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['reviewsID']],
      foreignColumns: [reviews.id],
      name: 'payload_locked_documents_rels_reviews_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site_settings_steps = pgTable(
  'site_settings_steps',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    body: varchar('body').notNull(),
  },
  (columns) => [
    index('site_settings_steps_order_idx').on(columns._order),
    index('site_settings_steps_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_steps_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_settings = pgTable('site_settings', {
  id: serial('id').primaryKey(),
  showBanner: boolean('show_banner').default(true),
  bannerText: varchar('banner_text').default(
    'Development build — products marked Sample are fictional. Real products stay hidden until an editor publishes them.',
  ),
  heroEyebrow: varchar('hero_eyebrow').default('Reviews from everywhere · one honest answer'),
  heroTitle: varchar('hero_title').default('Should you buy it? Every review, weighed.'),
  heroText: varchar('hero_text').default(
    'We read every review of a product across Amazon, Flipkart, Reddit and the app stores, set aside the ones that look fake, count what people actually say — and give you a straight answer.',
  ),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const scoring_rules = pgTable('scoring_rules', {
  id: serial('id').primaryKey(),
  buyScore: numeric('buy_score', { mode: 'number' }).notNull().default(7.5),
  caveatsScore: numeric('caveats_score', { mode: 'number' }).notNull().default(6),
  dealBreakerProblemRate: numeric('deal_breaker_problem_rate', { mode: 'number' })
    .notNull()
    .default(0.2),
  notableConProblemRate: numeric('notable_con_problem_rate', { mode: 'number' })
    .notNull()
    .default(0.1),
  minReviewsHigh: numeric('min_reviews_high', { mode: 'number' }).notNull().default(80),
  minReviewsMedium: numeric('min_reviews_medium', { mode: 'number' }).notNull().default(40),
  minMentionsPerAspect: numeric('min_mentions_per_aspect', { mode: 'number' }).notNull().default(5),
  minEvidencePerClaim: numeric('min_evidence_per_claim', { mode: 'number' }).notNull().default(2),
  suspiciousBelow: numeric('suspicious_below', { mode: 'number' }).notNull().default(0.3),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const catalog_state = pgTable('catalog_state', {
  id: serial('id').primaryKey(),
  version: numeric('version', { mode: 'number' }).default(0),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_products_claims = relations(products_claims, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_claims._parentID],
    references: [products.id],
    relationName: 'claims',
  }),
  aspect: one(aspects, {
    fields: [products_claims.aspect],
    references: [aspects.id],
    relationName: 'aspect',
  }),
}))
export const relations_products_faq = relations(products_faq, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_faq._parentID],
    references: [products.id],
    relationName: 'faq',
  }),
}))
export const relations_products_offers = relations(products_offers, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_offers._parentID],
    references: [products.id],
    relationName: 'offers',
  }),
  source: one(sources, {
    fields: [products_offers.source],
    references: [sources.id],
    relationName: 'source',
  }),
}))
export const relations_products_specs = relations(products_specs, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_specs._parentID],
    references: [products.id],
    relationName: 'specs',
  }),
}))
export const relations_products_platform_stats = relations(products_platform_stats, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_platform_stats._parentID],
    references: [products.id],
    relationName: 'platformStats',
  }),
  source: one(sources, {
    fields: [products_platform_stats.source],
    references: [sources.id],
    relationName: 'source',
  }),
}))
export const relations_products = relations(products, ({ one, many }) => ({
  brand: one(brands, {
    fields: [products.brand],
    references: [brands.id],
    relationName: 'brand',
  }),
  category: one(categories, {
    fields: [products.category],
    references: [categories.id],
    relationName: 'category',
  }),
  claims: many(products_claims, {
    relationName: 'claims',
  }),
  faq: many(products_faq, {
    relationName: 'faq',
  }),
  offers: many(products_offers, {
    relationName: 'offers',
  }),
  specs: many(products_specs, {
    relationName: 'specs',
  }),
  platformStats: many(products_platform_stats, {
    relationName: 'platformStats',
  }),
  author: one(users, {
    fields: [products.author],
    references: [users.id],
    relationName: 'author',
  }),
}))
export const relations__products_v_version_claims = relations(
  _products_v_version_claims,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_claims._parentID],
      references: [_products_v.id],
      relationName: 'version_claims',
    }),
    aspect: one(aspects, {
      fields: [_products_v_version_claims.aspect],
      references: [aspects.id],
      relationName: 'aspect',
    }),
  }),
)
export const relations__products_v_version_faq = relations(_products_v_version_faq, ({ one }) => ({
  _parentID: one(_products_v, {
    fields: [_products_v_version_faq._parentID],
    references: [_products_v.id],
    relationName: 'version_faq',
  }),
}))
export const relations__products_v_version_offers = relations(
  _products_v_version_offers,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_offers._parentID],
      references: [_products_v.id],
      relationName: 'version_offers',
    }),
    source: one(sources, {
      fields: [_products_v_version_offers.source],
      references: [sources.id],
      relationName: 'source',
    }),
  }),
)
export const relations__products_v_version_specs = relations(
  _products_v_version_specs,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_specs._parentID],
      references: [_products_v.id],
      relationName: 'version_specs',
    }),
  }),
)
export const relations__products_v_version_platform_stats = relations(
  _products_v_version_platform_stats,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_platform_stats._parentID],
      references: [_products_v.id],
      relationName: 'version_platformStats',
    }),
    source: one(sources, {
      fields: [_products_v_version_platform_stats.source],
      references: [sources.id],
      relationName: 'source',
    }),
  }),
)
export const relations__products_v = relations(_products_v, ({ one, many }) => ({
  parent: one(products, {
    fields: [_products_v.parent],
    references: [products.id],
    relationName: 'parent',
  }),
  version_brand: one(brands, {
    fields: [_products_v.version_brand],
    references: [brands.id],
    relationName: 'version_brand',
  }),
  version_category: one(categories, {
    fields: [_products_v.version_category],
    references: [categories.id],
    relationName: 'version_category',
  }),
  version_claims: many(_products_v_version_claims, {
    relationName: 'version_claims',
  }),
  version_faq: many(_products_v_version_faq, {
    relationName: 'version_faq',
  }),
  version_offers: many(_products_v_version_offers, {
    relationName: 'version_offers',
  }),
  version_specs: many(_products_v_version_specs, {
    relationName: 'version_specs',
  }),
  version_platformStats: many(_products_v_version_platform_stats, {
    relationName: 'version_platformStats',
  }),
  version_author: one(users, {
    fields: [_products_v.version_author],
    references: [users.id],
    relationName: 'version_author',
  }),
}))
export const relations_categories_measures = relations(categories_measures, ({ one }) => ({
  _parentID: one(categories, {
    fields: [categories_measures._parentID],
    references: [categories.id],
    relationName: 'measures',
  }),
  aspect: one(aspects, {
    fields: [categories_measures.aspect],
    references: [aspects.id],
    relationName: 'aspect',
  }),
}))
export const relations_categories_faq = relations(categories_faq, ({ one }) => ({
  _parentID: one(categories, {
    fields: [categories_faq._parentID],
    references: [categories.id],
    relationName: 'faq',
  }),
}))
export const relations_categories = relations(categories, ({ one, many }) => ({
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
  measures: many(categories_measures, {
    relationName: 'measures',
  }),
  faq: many(categories_faq, {
    relationName: 'faq',
  }),
}))
export const relations_brands_same_as = relations(brands_same_as, ({ one }) => ({
  _parentID: one(brands, {
    fields: [brands_same_as._parentID],
    references: [brands.id],
    relationName: 'sameAs',
  }),
}))
export const relations_brands = relations(brands, ({ one, many }) => ({
  sameAs: many(brands_same_as, {
    relationName: 'sameAs',
  }),
  logo: one(media, {
    fields: [brands.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_best_lists_faq = relations(best_lists_faq, ({ one }) => ({
  _parentID: one(best_lists, {
    fields: [best_lists_faq._parentID],
    references: [best_lists.id],
    relationName: 'faq',
  }),
}))
export const relations_best_lists = relations(best_lists, ({ one, many }) => ({
  category: one(categories, {
    fields: [best_lists.category],
    references: [categories.id],
    relationName: 'category',
  }),
  aspect: one(aspects, {
    fields: [best_lists.aspect],
    references: [aspects.id],
    relationName: 'aspect',
  }),
  faq: many(best_lists_faq, {
    relationName: 'faq',
  }),
}))
export const relations__best_lists_v_version_faq = relations(
  _best_lists_v_version_faq,
  ({ one }) => ({
    _parentID: one(_best_lists_v, {
      fields: [_best_lists_v_version_faq._parentID],
      references: [_best_lists_v.id],
      relationName: 'version_faq',
    }),
  }),
)
export const relations__best_lists_v = relations(_best_lists_v, ({ one, many }) => ({
  parent: one(best_lists, {
    fields: [_best_lists_v.parent],
    references: [best_lists.id],
    relationName: 'parent',
  }),
  version_category: one(categories, {
    fields: [_best_lists_v.version_category],
    references: [categories.id],
    relationName: 'version_category',
  }),
  version_aspect: one(aspects, {
    fields: [_best_lists_v.version_aspect],
    references: [aspects.id],
    relationName: 'version_aspect',
  }),
  version_faq: many(_best_lists_v_version_faq, {
    relationName: 'version_faq',
  }),
}))
export const relations_comparisons_pick_if = relations(comparisons_pick_if, ({ one }) => ({
  _parentID: one(comparisons, {
    fields: [comparisons_pick_if._parentID],
    references: [comparisons.id],
    relationName: 'pickIf',
  }),
  product: one(products, {
    fields: [comparisons_pick_if.product],
    references: [products.id],
    relationName: 'product',
  }),
}))
export const relations_comparisons_rels = relations(comparisons_rels, ({ one }) => ({
  parent: one(comparisons, {
    fields: [comparisons_rels.parent],
    references: [comparisons.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [comparisons_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
}))
export const relations_comparisons = relations(comparisons, ({ one, many }) => ({
  pickIf: many(comparisons_pick_if, {
    relationName: 'pickIf',
  }),
  category: one(categories, {
    fields: [comparisons.category],
    references: [categories.id],
    relationName: 'category',
  }),
  _rels: many(comparisons_rels, {
    relationName: '_rels',
  }),
}))
export const relations__comparisons_v_version_pick_if = relations(
  _comparisons_v_version_pick_if,
  ({ one }) => ({
    _parentID: one(_comparisons_v, {
      fields: [_comparisons_v_version_pick_if._parentID],
      references: [_comparisons_v.id],
      relationName: 'version_pickIf',
    }),
    product: one(products, {
      fields: [_comparisons_v_version_pick_if.product],
      references: [products.id],
      relationName: 'product',
    }),
  }),
)
export const relations__comparisons_v_rels = relations(_comparisons_v_rels, ({ one }) => ({
  parent: one(_comparisons_v, {
    fields: [_comparisons_v_rels.parent],
    references: [_comparisons_v.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [_comparisons_v_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
}))
export const relations__comparisons_v = relations(_comparisons_v, ({ one, many }) => ({
  parent: one(comparisons, {
    fields: [_comparisons_v.parent],
    references: [comparisons.id],
    relationName: 'parent',
  }),
  version_pickIf: many(_comparisons_v_version_pick_if, {
    relationName: 'version_pickIf',
  }),
  version_category: one(categories, {
    fields: [_comparisons_v.version_category],
    references: [categories.id],
    relationName: 'version_category',
  }),
  _rels: many(_comparisons_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_guides_faq = relations(guides_faq, ({ one }) => ({
  _parentID: one(guides, {
    fields: [guides_faq._parentID],
    references: [guides.id],
    relationName: 'faq',
  }),
}))
export const relations_guides = relations(guides, ({ one, many }) => ({
  aspect: one(aspects, {
    fields: [guides.aspect],
    references: [aspects.id],
    relationName: 'aspect',
  }),
  section: one(categories, {
    fields: [guides.section],
    references: [categories.id],
    relationName: 'section',
  }),
  faq: many(guides_faq, {
    relationName: 'faq',
  }),
}))
export const relations__guides_v_version_faq = relations(_guides_v_version_faq, ({ one }) => ({
  _parentID: one(_guides_v, {
    fields: [_guides_v_version_faq._parentID],
    references: [_guides_v.id],
    relationName: 'version_faq',
  }),
}))
export const relations__guides_v = relations(_guides_v, ({ one, many }) => ({
  parent: one(guides, {
    fields: [_guides_v.parent],
    references: [guides.id],
    relationName: 'parent',
  }),
  version_aspect: one(aspects, {
    fields: [_guides_v.version_aspect],
    references: [aspects.id],
    relationName: 'version_aspect',
  }),
  version_section: one(categories, {
    fields: [_guides_v.version_section],
    references: [categories.id],
    relationName: 'version_section',
  }),
  version_faq: many(_guides_v_version_faq, {
    relationName: 'version_faq',
  }),
}))
export const relations_review_requests_subscribers = relations(
  review_requests_subscribers,
  ({ one }) => ({
    _parentID: one(review_requests, {
      fields: [review_requests_subscribers._parentID],
      references: [review_requests.id],
      relationName: 'subscribers',
    }),
  }),
)
export const relations_review_requests = relations(review_requests, ({ one, many }) => ({
  subscribers: many(review_requests_subscribers, {
    relationName: 'subscribers',
  }),
  product: one(products, {
    fields: [review_requests.product],
    references: [products.id],
    relationName: 'product',
  }),
}))
export const relations_aspects = relations(aspects, () => ({}))
export const relations_sources = relations(sources, () => ({}))
export const relations_reviews = relations(reviews, ({ one }) => ({
  product: one(products, {
    fields: [reviews.product],
    references: [products.id],
    relationName: 'product',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  photo: one(media, {
    fields: [users.photo],
    references: [media.id],
    relationName: 'photo',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    brandsID: one(brands, {
      fields: [payload_locked_documents_rels.brandsID],
      references: [brands.id],
      relationName: 'brands',
    }),
    'best-listsID': one(best_lists, {
      fields: [payload_locked_documents_rels['best-listsID']],
      references: [best_lists.id],
      relationName: 'best-lists',
    }),
    comparisonsID: one(comparisons, {
      fields: [payload_locked_documents_rels.comparisonsID],
      references: [comparisons.id],
      relationName: 'comparisons',
    }),
    guidesID: one(guides, {
      fields: [payload_locked_documents_rels.guidesID],
      references: [guides.id],
      relationName: 'guides',
    }),
    'review-requestsID': one(review_requests, {
      fields: [payload_locked_documents_rels['review-requestsID']],
      references: [review_requests.id],
      relationName: 'review-requests',
    }),
    aspectsID: one(aspects, {
      fields: [payload_locked_documents_rels.aspectsID],
      references: [aspects.id],
      relationName: 'aspects',
    }),
    sourcesID: one(sources, {
      fields: [payload_locked_documents_rels.sourcesID],
      references: [sources.id],
      relationName: 'sources',
    }),
    reviewsID: one(reviews, {
      fields: [payload_locked_documents_rels.reviewsID],
      references: [reviews.id],
      relationName: 'reviews',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site_settings_steps = relations(site_settings_steps, ({ one }) => ({
  _parentID: one(site_settings, {
    fields: [site_settings_steps._parentID],
    references: [site_settings.id],
    relationName: 'steps',
  }),
}))
export const relations_site_settings = relations(site_settings, ({ many }) => ({
  steps: many(site_settings_steps, {
    relationName: 'steps',
  }),
}))
export const relations_scoring_rules = relations(scoring_rules, () => ({}))
export const relations_catalog_state = relations(catalog_state, () => ({}))

type DatabaseSchema = {
  enum_products_claims_sentiment: typeof enum_products_claims_sentiment
  enum_products_status: typeof enum_products_status
  enum__products_v_version_claims_sentiment: typeof enum__products_v_version_claims_sentiment
  enum__products_v_version_status: typeof enum__products_v_version_status
  enum_categories_app_category: typeof enum_categories_app_category
  enum_best_lists_rank_by: typeof enum_best_lists_rank_by
  enum_best_lists_status: typeof enum_best_lists_status
  enum__best_lists_v_version_rank_by: typeof enum__best_lists_v_version_rank_by
  enum__best_lists_v_version_status: typeof enum__best_lists_v_version_status
  enum_comparisons_status: typeof enum_comparisons_status
  enum__comparisons_v_version_status: typeof enum__comparisons_v_version_status
  enum_guides_status: typeof enum_guides_status
  enum__guides_v_version_status: typeof enum__guides_v_version_status
  enum_review_requests_status: typeof enum_review_requests_status
  enum_sources_kind: typeof enum_sources_kind
  enum_reviews_sentiment: typeof enum_reviews_sentiment
  enum_users_role: typeof enum_users_role
  products_claims: typeof products_claims
  products_faq: typeof products_faq
  products_offers: typeof products_offers
  products_specs: typeof products_specs
  products_platform_stats: typeof products_platform_stats
  products: typeof products
  _products_v_version_claims: typeof _products_v_version_claims
  _products_v_version_faq: typeof _products_v_version_faq
  _products_v_version_offers: typeof _products_v_version_offers
  _products_v_version_specs: typeof _products_v_version_specs
  _products_v_version_platform_stats: typeof _products_v_version_platform_stats
  _products_v: typeof _products_v
  categories_measures: typeof categories_measures
  categories_faq: typeof categories_faq
  categories: typeof categories
  brands_same_as: typeof brands_same_as
  brands: typeof brands
  best_lists_faq: typeof best_lists_faq
  best_lists: typeof best_lists
  _best_lists_v_version_faq: typeof _best_lists_v_version_faq
  _best_lists_v: typeof _best_lists_v
  comparisons_pick_if: typeof comparisons_pick_if
  comparisons: typeof comparisons
  comparisons_rels: typeof comparisons_rels
  _comparisons_v_version_pick_if: typeof _comparisons_v_version_pick_if
  _comparisons_v: typeof _comparisons_v
  _comparisons_v_rels: typeof _comparisons_v_rels
  guides_faq: typeof guides_faq
  guides: typeof guides
  _guides_v_version_faq: typeof _guides_v_version_faq
  _guides_v: typeof _guides_v
  review_requests_subscribers: typeof review_requests_subscribers
  review_requests: typeof review_requests
  aspects: typeof aspects
  sources: typeof sources
  reviews: typeof reviews
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_settings_steps: typeof site_settings_steps
  site_settings: typeof site_settings
  scoring_rules: typeof scoring_rules
  catalog_state: typeof catalog_state
  relations_products_claims: typeof relations_products_claims
  relations_products_faq: typeof relations_products_faq
  relations_products_offers: typeof relations_products_offers
  relations_products_specs: typeof relations_products_specs
  relations_products_platform_stats: typeof relations_products_platform_stats
  relations_products: typeof relations_products
  relations__products_v_version_claims: typeof relations__products_v_version_claims
  relations__products_v_version_faq: typeof relations__products_v_version_faq
  relations__products_v_version_offers: typeof relations__products_v_version_offers
  relations__products_v_version_specs: typeof relations__products_v_version_specs
  relations__products_v_version_platform_stats: typeof relations__products_v_version_platform_stats
  relations__products_v: typeof relations__products_v
  relations_categories_measures: typeof relations_categories_measures
  relations_categories_faq: typeof relations_categories_faq
  relations_categories: typeof relations_categories
  relations_brands_same_as: typeof relations_brands_same_as
  relations_brands: typeof relations_brands
  relations_best_lists_faq: typeof relations_best_lists_faq
  relations_best_lists: typeof relations_best_lists
  relations__best_lists_v_version_faq: typeof relations__best_lists_v_version_faq
  relations__best_lists_v: typeof relations__best_lists_v
  relations_comparisons_pick_if: typeof relations_comparisons_pick_if
  relations_comparisons_rels: typeof relations_comparisons_rels
  relations_comparisons: typeof relations_comparisons
  relations__comparisons_v_version_pick_if: typeof relations__comparisons_v_version_pick_if
  relations__comparisons_v_rels: typeof relations__comparisons_v_rels
  relations__comparisons_v: typeof relations__comparisons_v
  relations_guides_faq: typeof relations_guides_faq
  relations_guides: typeof relations_guides
  relations__guides_v_version_faq: typeof relations__guides_v_version_faq
  relations__guides_v: typeof relations__guides_v
  relations_review_requests_subscribers: typeof relations_review_requests_subscribers
  relations_review_requests: typeof relations_review_requests
  relations_aspects: typeof relations_aspects
  relations_sources: typeof relations_sources
  relations_reviews: typeof relations_reviews
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_settings_steps: typeof relations_site_settings_steps
  relations_site_settings: typeof relations_site_settings
  relations_scoring_rules: typeof relations_scoring_rules
  relations_catalog_state: typeof relations_catalog_state
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
