/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    brands: Brand;
    'best-lists': BestList;
    comparisons: Comparison;
    guides: Guide;
    'review-requests': ReviewRequest;
    pages: Page;
    tags: Tag;
    media: Media;
    aspects: Aspect;
    sources: Source;
    reviews: Review;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      products: 'products';
    };
    brands: {
      products: 'products';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'best-lists': BestListsSelect<false> | BestListsSelect<true>;
    comparisons: ComparisonsSelect<false> | ComparisonsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'review-requests': ReviewRequestsSelect<false> | ReviewRequestsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    aspects: AspectsSelect<false> | AspectsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    'scoring-rules': ScoringRule;
    'catalog-state': CatalogState;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'scoring-rules': ScoringRulesSelect<false> | ScoringRulesSelect<true>;
    'catalog-state': CatalogStateSelect<false> | CatalogStateSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every product we review. Draft products are hidden from the site: read the draft with Preview, then press Publish to approve it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Used in tables and comparisons, e.g. "Airdopes 141 Gen 2".
   */
  shortName: string;
  brand: number | Brand;
  category: number | Category;
  variant?: string | null;
  /**
   * Sample products are made up for development and labelled "Sample" on the site.
   */
  sample?: boolean | null;
  /**
   * The first thing readers see: the verdict in one or two sentences, up to 320 characters. No statistics.
   */
  answer: string;
  /**
   * Two short paragraphs. Leave a blank line between them.
   */
  verdictBody?: string | null;
  /**
   * Each one needs at least two reviews behind it — ones without enough evidence are hidden automatically. The page adds the percentage and a quote.
   */
  claims?:
    | {
        sentiment: 'positive' | 'negative';
        aspect: number | Aspect;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the page and marked up for search engines. Phrase questions the way people ask them.
   */
  faq?:
    | {
        q: string;
        /**
         * About 40–60 words. No statistics — the page shows every figure next to the text.
         */
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One row per store. Use 0 for free apps.
   */
  offers?:
    | {
        source: number | Source;
        price: number;
        mrp?: number | null;
        inStock?: boolean | null;
        url?: string | null;
        checkedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only if the category shows a price per unit: e.g. grams of protein in the pack. Leave 0 if unknown.
   */
  valueQuantity?: number | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  flipkartUrl?: string | null;
  playStoreId?: string | null;
  appStoreId?: string | null;
  /**
   * Comma-separated, e.g. "Airdopes 141, boAt Airdopes".
   */
  redditPhrases?: string | null;
  /**
   * Each store’s own rating and rating count, as the store reports them.
   */
  platformStats?:
    | {
        source: number | Source;
        rating: number;
        total: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the page as "Updated". Moves only when new reviews are collected.
   */
  dataUpdatedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * The page lives at /reviews/<this>. Filled in from the name; don’t change it after publishing.
   */
  slug: string;
  /**
   * Group this with related pages. Each tag has its own page listing everything tagged with it.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Set automatically to whoever publishes.
   */
  author?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every brand gets its own page listing its products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * A short, factual description. Leave a blank line between paragraphs.
   */
  about?: string | null;
  website?: string | null;
  /**
   * e.g. the brand’s Wikipedia or Wikidata page. Helps search engines identify the brand.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * The brand’s page lives at /brands/<this>.
   */
  slug: string;
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Every image on the site: product photos, logos, page images and share images. Drag an image in, write what it shows, and optionally click the point that must never be cropped.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and search engines.
   */
  alt: string;
  /**
   * Optional. Shown under the image where there is room.
   */
  caption?: string | null;
  /**
   * Optional. Photographer or source, e.g. "Photo: boAt".
   */
  credit?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    share?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sections (like "Apps") and the categories inside them (like "UPI & Payment Apps"). Every product belongs to one category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Leave empty to make this a top-level section (shown in the menu). Pick a section to make this a category inside it.
   */
  parent?: (number | null) | Category;
  /**
   * One sentence under the title, e.g. "Every whey protein we track, scored on the same measures."
   */
  tagline: string;
  /**
   * Two or three short paragraphs on what matters when buying in this category. Leave a blank line between paragraphs.
   */
  intro?: string | null;
  measures?:
    | {
        aspect: number | Aspect;
        /**
         * If too many reviewers report a problem with this, the product is marked Skip however good the rest is.
         */
        dealBreaker?: boolean | null;
        /**
         * Leave at 1 unless you have a reason. Kept for future scoring.
         */
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Lets product cards show a comparable price, e.g. "per 100 g protein". Each product then needs its unit count.
   */
  valueMetric?: {
    label?: string | null;
    basis?: number | null;
  };
  /**
   * Apps are free, so pages say "Use it" instead of "Buy" and show store ratings.
   */
  isApp?: boolean | null;
  appCategory?:
    | (
        | 'FinanceApplication'
        | 'ShoppingApplication'
        | 'LifestyleApplication'
        | 'TravelApplication'
        | 'HealthApplication'
        | 'EntertainmentApplication'
        | 'UtilitiesApplication'
      )
    | null;
  /**
   * Shown on the page and marked up for search engines. Phrase questions the way people ask them.
   */
  faq?:
    | {
        q: string;
        /**
         * About 40–60 words. No statistics — the page shows every figure next to the text.
         */
        a: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * Sections live at /<this>, categories at /<section>/<this>. Changing it later redirects the old address.
   */
  slug: string;
  /**
   * How often reviews for products in this category are re-collected.
   */
  refreshDays?: number | null;
  /**
   * Products in this category.
   */
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * The things products are judged on, like taste or payment success. Categories choose which measures apply to them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aspects".
 */
export interface Aspect {
  id: number;
  label: string;
  /**
   * How a shopper would ask about it.
   */
  question: string;
  /**
   * Internal key the review analysis uses. Filled in from the name; don’t change it once reviews have been analysed.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Where reviews come from. Listed publicly on the "Where our reviews come from" page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  kind: 'marketplace' | 'brand-store' | 'app-store' | 'community' | 'video';
  /**
   * How much its star ratings count in our weighted average. Brand-owned stores are down-weighted (0.6).
   */
  weight: number;
  /**
   * Off for Reddit and YouTube, where people write without a star rating.
   */
  hasRatings?: boolean | null;
  collection: string;
  /**
   * Internal key used by the review pipeline, e.g. play-store.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Labels that group related pages, e.g. "Budget picks". Add them from the sidebar of any product, list, guide or page. Each tag has a page at /tags/<web address> listing everything with it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Shown at the top of the tag’s page. A sentence or two on what ties these together.
   */
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * The tag’s page lives at /tags/<this>.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Everyone who can log in. Editors approve verdicts, and their name and bio appear on every page they publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown on every verdict you approve, e.g. "Approved by Omkar".
   */
  name?: string | null;
  /**
   * Address of your public profile page, /authors/…
   */
  slug?: string | null;
  /**
   * Editors write and publish. Admins can also manage the team and the scoring rules.
   */
  role?: ('admin' | 'editor') | null;
  jobTitle?: string | null;
  /**
   * A few sentences for your public profile page.
   */
  bio?: string | null;
  /**
   * Optional, e.g. "Certified nutritionist".
   */
  credentials?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Pages like "Best whey protein under ₹2,500". You choose the rule; the ranking updates itself as reviews and prices change. Products marked Skip are never ranked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "best-lists".
 */
export interface BestList {
  id: number;
  title: string;
  /**
   * Pick a section to rank products from all its categories together.
   */
  category: number | Category;
  /**
   * What makes this list different from the category page, e.g. "under ₹2,500" or "without bloating". Lists without one compete with their own category in search.
   */
  qualifier: string;
  /**
   * Why these products, and how they are ranked.
   */
  intro?: string | null;
  rankBy: 'satisfaction' | 'fewest-problems';
  aspect?: (number | null) | Aspect;
  /**
   * Optional.
   */
  maxPrice?: number | null;
  /**
   * Shown on the page and marked up for search engines. Phrase questions the way people ask them.
   */
  faq?:
    | {
        q: string;
        /**
         * About 40–60 words. No statistics — the page shows every figure next to the text.
         */
        a: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * The page lives at /best/<this>.
   */
  slug: string;
  /**
   * Group this with related pages. Each tag has its own page listing everything tagged with it.
   */
  tags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Two products side by side. Pick two from the same category; the table fills itself in. Whole-category tables are made automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons".
 */
export interface Comparison {
  id: number;
  /**
   * Exactly two products from the same category.
   */
  products: (number | Product)[];
  /**
   * Which suits whom, in a paragraph or two. Leave a blank line between paragraphs.
   */
  judgement: string;
  pickIf?:
    | {
        product: number | Product;
        text: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * Taken from the products.
   */
  category?: (number | null) | Category;
  /**
   * Made from the two products: /compare/<this>.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Explainers about one measure across a whole section, e.g. "Does protein powder cause bloating?". The ranking of products fills itself in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  /**
   * Phrase it as the question people search for.
   */
  title: string;
  aspect: number | Aspect;
  section: number | Category;
  /**
   * A few paragraphs explaining the issue. Leave a blank line between paragraphs.
   */
  explainer: string;
  /**
   * Shown on the page and marked up for search engines. Phrase questions the way people ask them.
   */
  faq?:
    | {
        q: string;
        /**
         * About 40–60 words. No statistics — the page shows every figure next to the text.
         */
        a: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * The page lives at /topics/<this>.
   */
  slug: string;
  /**
   * Group this with related pages. Each tag has its own page listing everything tagged with it.
   */
  tags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Products readers asked us to review. Most-requested first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-requests".
 */
export interface ReviewRequest {
  id: number;
  /**
   * What the reader typed.
   */
  query: string;
  /**
   * Optional link the reader gave (Amazon, Flipkart, Google Play, App Store).
   */
  productUrl?: string | null;
  /**
   * Readers who asked to be emailed once, when the review goes live.
   */
  subscribers?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Once the product is in the catalogue, link it here and set the status to "Added to catalogue".
   */
  product?: (number | null) | Product;
  /**
   * Internal notes. Never shown on the site.
   */
  notes?: string | null;
  status: 'new' | 'queued' | 'added' | 'declined';
  requestCount: number;
  lastRequestedAt?: string | null;
  /**
   * Used to merge repeat requests.
   */
  normalizedQuery: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your own pages: About, Contact, Privacy policy and so on. Each lives at /<web address>. Add them to the menu or footer under Website → Navigation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Optional. A sentence or two shown in large type under the title.
   */
  intro?: string | null;
  /**
   * Optional. Shown under the summary, full width.
   */
  heroImage?: (number | null) | Media;
  /**
   * Write as in a word processor. Type "/" for headings, lists, images, quotes, highlighted notes and buttons.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The page stays on the site, but Google and others are asked not to list it.
     */
    noindex?: boolean | null;
    /**
     * Only if this page copies another one: the address of the original. Leave empty otherwise.
     */
    canonical?: string | null;
  };
  /**
   * The page lives at /<this>. Changing it later sends the old address to the new one automatically.
   */
  slug: string;
  /**
   * Group this with related pages. Each tag has its own page listing everything tagged with it.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Set automatically the first time you publish.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every collected review. They come in automatically and can’t be edited — but you can hide one (spam, abuse, wrong product) and it disappears from the site and the numbers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Hidden reviews are left out of every page and every number.
   */
  hidden?: boolean | null;
  product: number | Product;
  body: string;
  source: string;
  rating?: number | null;
  sentiment?: ('positive' | 'neutral' | 'negative') | null;
  author?: string | null;
  date?: string | null;
  verified?: boolean | null;
  /**
   * 0–1. Below 0.3 counts as likely manipulated.
   */
  credibility?: number | null;
  url?: string | null;
  aspects?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  original?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old address to a new one, so old links and search results keep working. Made for you when you change a published page’s web address.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'categories';
          value: number | Category;
        } | null)
      | ({
          relationTo: 'brands';
          value: number | Brand;
        } | null)
      | ({
          relationTo: 'best-lists';
          value: number | BestList;
        } | null)
      | ({
          relationTo: 'comparisons';
          value: number | Comparison;
        } | null)
      | ({
          relationTo: 'guides';
          value: number | Guide;
        } | null)
      | ({
          relationTo: 'tags';
          value: number | Tag;
        } | null);
    url?: string | null;
  };
  /**
   * Permanent (301) unless the old address will come back.
   */
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'best-lists';
        value: number | BestList;
      } | null)
    | ({
        relationTo: 'comparisons';
        value: number | Comparison;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'review-requests';
        value: number | ReviewRequest;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'aspects';
        value: number | Aspect;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  brand?: T;
  category?: T;
  variant?: T;
  sample?: T;
  answer?: T;
  verdictBody?: T;
  claims?:
    | T
    | {
        sentiment?: T;
        aspect?: T;
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  offers?:
    | T
    | {
        source?: T;
        price?: T;
        mrp?: T;
        inStock?: T;
        url?: T;
        checkedAt?: T;
        id?: T;
      };
  valueQuantity?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  flipkartUrl?: T;
  playStoreId?: T;
  appStoreId?: T;
  redditPhrases?: T;
  platformStats?:
    | T
    | {
        source?: T;
        rating?: T;
        total?: T;
        id?: T;
      };
  dataUpdatedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  tags?: T;
  author?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  tagline?: T;
  intro?: T;
  measures?:
    | T
    | {
        aspect?: T;
        dealBreaker?: T;
        weight?: T;
        id?: T;
      };
  valueMetric?:
    | T
    | {
        label?: T;
        basis?: T;
      };
  isApp?: T;
  appCategory?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  refreshDays?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  about?: T;
  website?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  logo?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "best-lists_select".
 */
export interface BestListsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  qualifier?: T;
  intro?: T;
  rankBy?: T;
  aspect?: T;
  maxPrice?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons_select".
 */
export interface ComparisonsSelect<T extends boolean = true> {
  products?: T;
  judgement?: T;
  pickIf?:
    | T
    | {
        product?: T;
        text?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  category?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  aspect?: T;
  section?: T;
  explainer?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-requests_select".
 */
export interface ReviewRequestsSelect<T extends boolean = true> {
  query?: T;
  productUrl?: T;
  subscribers?:
    | T
    | {
        email?: T;
        id?: T;
      };
  product?: T;
  notes?: T;
  status?: T;
  requestCount?: T;
  lastRequestedAt?: T;
  normalizedQuery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  heroImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  tags?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        canonical?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        share?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aspects_select".
 */
export interface AspectsSelect<T extends boolean = true> {
  label?: T;
  question?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  weight?: T;
  hasRatings?: T;
  collection?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  hidden?: T;
  product?: T;
  body?: T;
  source?: T;
  rating?: T;
  sentiment?: T;
  author?: T;
  date?: T;
  verified?: T;
  credibility?: T;
  url?: T;
  aspects?: T;
  original?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  jobTitle?: T;
  bio?: T;
  credentials?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The links in the menu at the top and the footer at the bottom of every page. Categories, ranked lists and comparisons are listed automatically; these are the links you choose.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Shown after "Categories" in the top menu. Leave empty for the standard links: Best lists, Compare, How we score.
   */
  headerLinks?:
    | {
        label: string;
        type?: ('page' | 'custom') | null;
        page?: (number | null) | Page;
        /**
         * A path on this site (/best) or a full address.
         */
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Columns of links in the footer, e.g. "Company" with About and Contact. Leave empty for the standard "Trust" column.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              type?: ('page' | 'custom') | null;
              page?: (number | null) | Page;
              /**
               * A path on this site (/best) or a full address.
               */
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerAbout?: string | null;
  /**
   * Shown at the very bottom, after "© <year> ReviewLens."
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage wording, the banner, search engine settings, social profiles and analytics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  showBanner?: boolean | null;
  bannerText?: string | null;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroText?: string | null;
  steps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Turn on while the site is on a temporary address or not ready. Search engines are asked not to list any page. Turn off when you launch.
   */
  hideFromSearch?: boolean | null;
  /**
   * Used by search results and link previews for pages without their own description. Up to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * The picture shown when a link is shared on WhatsApp, X, LinkedIn and so on, unless the page has its own. 1200 × 630 works best.
   */
  shareImage?: (number | null) | Media;
  /**
   * A square logo. Search engines may show it next to your results.
   */
  logo?: (number | null) | Media;
  /**
   * Only the content="…" value from the HTML tag Google gives you.
   */
  googleVerification?: string | null;
  /**
   * Only the content="…" value.
   */
  bingVerification?: string | null;
  twitterHandle?: string | null;
  /**
   * Links to your Instagram, X, YouTube, LinkedIn and so on. Search engines use them to recognise the brand.
   */
  socialProfiles?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste the ID from Google Analytics 4 to start counting visits. Leave empty for no analytics.
   */
  gaMeasurementId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The thresholds every verdict is decided by. The "How we score" page shows these exact values. Admins only — changing one changes verdicts across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scoring-rules".
 */
export interface ScoringRule {
  id: number;
  buyScore: number;
  caveatsScore: number;
  /**
   * 0.2 = one in five reviewers report a problem.
   */
  dealBreakerProblemRate: number;
  notableConProblemRate: number;
  minReviewsHigh: number;
  /**
   * Below this the verdict is "Not enough data".
   */
  minReviewsMedium: number;
  minMentionsPerAspect: number;
  minEvidencePerClaim: number;
  suspiciousBelow: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-state".
 */
export interface CatalogState {
  id: number;
  version?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  footerAbout?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  showBanner?: T;
  bannerText?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroText?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  hideFromSearch?: T;
  metaDescription?: T;
  shareImage?: T;
  logo?: T;
  googleVerification?: T;
  bingVerification?: T;
  twitterHandle?: T;
  socialProfiles?:
    | T
    | {
        url?: T;
        id?: T;
      };
  gaMeasurementId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scoring-rules_select".
 */
export interface ScoringRulesSelect<T extends boolean = true> {
  buyScore?: T;
  caveatsScore?: T;
  dealBreakerProblemRate?: T;
  notableConProblemRate?: T;
  minReviewsHigh?: T;
  minReviewsMedium?: T;
  minMentionsPerAspect?: T;
  minEvidencePerClaim?: T;
  suspiciousBelow?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-state_select".
 */
export interface CatalogStateSelect<T extends boolean = true> {
  version?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}